[package]
name = "cypher_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"
proc-macro-error = "1"
proc_macro_roids = "0.7.0"